project: 
  title: "BiostatMoon"
  type: website
  execute-dir: project
  output-dir: docs
  preview: 
    port: 7777
    browser: false

execute: 
  freeze: auto

website: 
  title: BiostatMoon
  favicon: images/profile.png
  image: images/profile.png
  search:
    location: navbar
    type: textbox
  navbar:
    logo: images/profile.png
    logo-href: index.qmd
    left: 
      - qmds/index.qmd
      - qmds/記事一覧.qmd
      - qmds/管理者.qmd
      - qmds/実行環境.qmd
      - qmds/お問い合わせ.qmd
    tools:
      - icon: github
        href: https://github.com/yasuih777/biostatmoon
      - icon: twitter
        href: https://twitter.com/yugetsubiostat
  sidebar:
    - title: ページリンク
      style: "docked"
      pinned: false
      contents: qmds
  back-to-top-navigation: true
  page-footer: Copyright 2024, 優月 

title: Non title
date: now
date-modified: now
date-format: iso
abstract: Non abstract
order: 0
link-external-icon: true
link-external-newwindow: true
format:
  html:
    theme: minty
    css: styles.css
    grid:
      body-width: 1440px
      gutter-width: 10px
    linestretch: 2em
    toc: true
    anchor-sections: true
    smooth-scroll: true
    quarto-required: ">= 1.3.450"

jupyter: python3
code-line-numbers: true
code-annotations: hover
code-fold: true

fig-cap-location: margin

license: CC BY 4.0 DEED
