---
title: 整然データ
abstract: 分析や可視化に向いているデータ構造について
date: now
date-modified: now
categories:
    - データサイエンス
    - データエンジニアリング
order: 1
---

# 整然データ

**整然データ**は、2014年にHadley Wickham氏が[Tidy data](https://www.jstatsoft.org/article/view/v059i10)として提唱した、分析および可視化を容易にするためのフレームワークである。データ構造をこの整然データのルールに沿って作っていくことで、機械によるデータの操作を容易にし、プログラミングによるデータ処理・可視化・統計モデリングを決まった手順で行うことができる。  
整然データはリレーショナルデータベース(RDB)の原理に密接に関わっている。いわゆるRDBのトランザクションデータが整然データと互換性があるが、整然データはより統計家が慣れ親しんだ言葉で解釈される。

## 整然データの条件
整然データの条件として、以下の四つがある。

1. **個々の変数が一つの列をなす**
2. **個々の観測が一つの行をなす**
3. **個々の観測の構成単位の類型が一つの表をなす**
4. **個々の値が一つのセルをなす**

::: {.callout-tip}
## Example
次のような @tbl-tidy が整然データである。ここでは、学期末に行われるテストの点数を例とした。

| 名前 | 学期 | 点数 |
| --- | --- | --- |
| 佐藤 | 一学期 | 320 |
| 佐藤 | 二学期 | 300 |
| 佐藤 | 三学期 | 350 |
| 田中 | 一学期 | 410 |
| 田中 | 二学期 | 420 |
| 田中 | 三学期 | 390 |
| 鈴木 | 一学期 | 290 |
| 鈴木 | 二学期 | 290 |
| 鈴木 | 三学期 | 300 |

: 整然データ {#tbl-tidy .striped}

:::

@tbl-tidy をみると整然データの条件を満たしていることが分かる。  
即ち、一つの列に同じ意味を持つデータが格納されており、一つの行が一回のテストの結果を表しており、テストの結果以外の観測は入っておらず、一つのセルに一つの値のみが入っている。

# 雑然データ
整然データの条件を満たさないデータ構造を**雑然データ**と呼ぶ。我々人が見やすい表構造はほとんどがこの雑然データに該当する。

::: {.callout-tip}
## Example
次のような @tbl-messy が整然データである。これは、 @tbl-tidy と同じデータで構造を変えたものである。

| 名前 | 一学期 | 二学期 | 三学期 |
| --- | --- | --- | --- |
| 佐藤 | 320| 300 | 350 |
| 田中 | 410 | 420 | 390 |
| 鈴木 | 290 | 290 | 300 |

: 整然データ {#tbl-messy .striped}

:::

@tbl-messy は整然データではない、即ち雑然データである。  
プログラミング言語は基本的にデータをベクトルとして扱うため、このように同じ意味を持つデータが複数列にまたがっている場合に一度にデータ全てを取り出すことができない。一方で、整然データは一つの列を取り出すことでデータを取り出すことができるので、以降のデータ処理も効率よく行うことができる。

## 雑然データの条件
雑然データは整然データでないものすべてが該当するため、[整然データの条件](#整然データの条件)で取り上げた四つの条件いずれかを満たさない。これがどのようなデータ構造となるか考えていく。

1. **個々の変数が一つの列をなす**

@tbl-messy がこれにあたる。これは、テストの結果が3列にまたがっているため整然データではない。

2. **個々の観測が一つの行をなす**

これも @tbl-messy が例としてあたる。「佐藤」の行を取り出すことに三学期分のテスト結果全てを取り出すこととなり、個々のテストの結果となっていない。

3. **個々の観測の構成単位の類型が一つの表をなす**

| 名前 | 学期 | 点数 |
| --- | --- | --- |
| 佐藤 | 一学期 | 320 |
| 佐藤 | 二学期 | 300 |
| 佐藤 | 三学期 | 350 |
| 佐藤 | 三学期 | B |
| 田中 | 一学期 | 410 |
| 田中 | 二学期 | 420 |
| 田中 | 三学期 | 390 |
| 佐藤 | 三学期 | B |
| 鈴木 | 一学期 | 290 |
| 鈴木 | 二学期 | 290 |
| 鈴木 | 三学期 | 300 |
| 佐藤 | 三学期 | C |

: 複数の構成単位をもつ表構造 {#tbl-multi .striped}

@tbl-multi がこの例にあたる。構成単位の類型とは簡単に言うと観測の種類なので、これが複数あるとは種類の異なる観測が一つの表に含まれているということである。この例では、三学期のテストの結果の後に三段階の成績が観測として挿入されているため、雑然データである。

4. **個々の値が一つのセルをなす**

| 名前 | 学期 | 点数 |
| --- | --- | --- |
| 佐藤 | 一学期 二学期 三学期 | 970 |
| 田中 | 一学期 二学期 三学期 | 1220 |
| 鈴木 | 一学期 二学期 三学期 | 880 |

: 複数の値が一つのセルに入っている表構造 {#tbl-concat .striped}

@tbl-concat がこの例にあたる。学期に三種類の値が入っているため整然データの条件を満たさない。神エクセルでよくみられる。

## 整然化
雑然データを整然データに変換することを**整然化**と呼ぶ。整然化の方法として融解・文字列操作・キャスティングなどがある。これらの操作はRの`tibble`や、Pythonの`Polars`または`Pandas`で関数化されている。