---
title: "ホーム"
abstract: ホームページ
date: 01-21-2024
date-modified: 01-21-2024
---

# このサイトについて
管理者(優月)が生物統計(+その他の技術諸々)について学んだことを書いていきます。レベル感としては、統計家が適切な判断によってデータ分析ができるようになることを目標としています。

- [記事一覧](%E8%A8%98%E4%BA%8B%E4%B8%80%E8%A6%A7.qmd): 書いたコンテンツをまとめています。左のサイドバーでもリスティングしています。
- [管理者](%E7%AE%A1%E7%90%86%E8%80%85.qmd): 管理者である優月の紹介ページです。
- [実行環境](%E5%AE%9F%E8%A1%8C%E7%92%B0%E5%A2%83.qmd): このサイトを構成している環境を書いています。(メインエンジンは[Quarto](https://quarto.org/)使っています)
- [お問い合わせ](%E3%81%8A%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B.qmd): お問い合わせがございましたらこちらからよろしくお願い致します。

# 免責事項

- 本サイトに掲載されている情報は、正確である保証はありません。
- 本サイトに掲載されている情報は、私個人の見解である。所属機関を代表する見解ではありません。
- 本サイトを利用して、あなたに損害が生じても、一切責任を負いません。
- 本サイトのコンテンツは、予告なく変更や公開の取り消しする場合があります。

---

# ライセンス

## ブログ内のコンテンツ
本サイトにおける各エントリの文章や画像などのコンテンツは[クリエイティブ・コモンズ・ライセンス](https://creativecommons.org/licenses/by/4.0/deed.ja)を適応します。

## ブログ内サンプルコードのライセンス
ブログ内で書いているコードに関しては例外的にMIT Licenceを適応します。

:::{.callout-note collapse="true"}
## MIT License

Copyright 2024 優月

以下に定める条件に従い、本ソフトウェアおよび関連文書のファイル（以下「ソフトウェア」）の複製を取得するすべての人に対し、ソフトウェアを無制限に扱うことを無償で許可します。これには、ソフトウェアの複製を使用、複写、変更、結合、掲載、頒布、サブライセンス、および/または販売する権利、およびソフトウェアを提供する相手に同じことを許可する権利も無制限に含まれます。

上記の著作権表示および本許諾表示を、ソフトウェアのすべての複製または重要な部分に記載するものとします。

ソフトウェアは「現状のまま」で、明示であるか暗黙であるかを問わず、何らの保証もなく提供されます。ここでいう保証とは、商品性、特定の目的への適合性、および権利非侵害についての保証も含みますが、それに限定されるものではありません。 作者または著作権者は、契約行為、不法行為、またはそれ以外であろうと、ソフトウェアに起因または関連し、あるいはソフトウェアの使用またはその他の扱いによって生じる一切の請求、損害、その他の義務について何らの責任も負わないものとします。
:::