---
title: 推定
abstract: 統計学の中心である母数の推定
date: 02-04-2024
date-modified: 02-06-2024
categories:
    - 確率統計
order: 3
---

# 標本抽出

## 母集団・標本
解析対象として考慮する集団全体を**母集団**という。しかし、母集団が非常に多くの要素を含む、個々の観測のコストが高い、未来の事象も対象に含むなど母集団全体を解析することが困難な場合が多い。このようなとき母集団の一部を選択し、それらを解析し、母集団の特性を推測するということを行う。これを**統計的推測** @fig-estimate と呼ぶ。また、このようにして母集団の一部として選ばれた要素を**標本**、選び出すことを**標本抽出(抽出)**と呼ぶ。  
※母集団全体を標本として調査することを**全数調査(悉皆調査)**という。

## 抽出方法
標本抽出の方法として大きく以下の二つがある。母集団の要素数が十分に大きい場合はほとんど差がない。

- **復元抽出**: 抽出した標本を再び母集団に戻す方法
- **非復元抽出**: 一度抽出した標本を母集団に戻さない方法
    - 普段の実験や観測ではこちらが行われる

また、標本の選び方として以下の二つがある。エピデンスレベルが高いのは無作為抽出だが、一方で有意抽出の方が低コストで調査を行えるというメリデメがある。

- **無作為抽出**: 標本をランダムに選択し、抽出
- **有意抽出**: 標本を恣意的に選択し、抽出

## 母集団分布・標本分布
統計理論において解析の対象となるのは母集団の特性である。ここでいう特性とは、母集団がもつ分布(**母集団分布**)である。標本はこの母集団分布に基づいて取り出されることになるので、標本$x_{1}, x_{2}, \cdots, x_{n}$は互いに独立で、母集団分布$P$に従う。  
ここで抽出した標本の数$n$を**サンプルサイズ**と呼ぶ。

```{dot}
//| label: fig-estimate
//| fig-cap: 統計的推測
//| fig-height: 250px

digraph G {
    newrank=true
    graph [nodesep=.8]

    subgraph cluster_population{
        cluster = true
        label = "Population distribution"

        population [label="Population"]
        parameter [label="Parameter" shape=underline]
    }

    subgraph cluster_sample{
        style=invis

        sample [label="Sample" shape=cylinder]
        estimate [label="Estimate" shape=box]
    }

    population -> sample [label="sampling" style="dashed"]
    sample -> estimate [label="analysis"]
    estimate -> parameter [label="inference"]

    {rank=same; population; sample}
    {rank=same; estimate; parameter}
}
```

## パラメトリック・ノンパラメトリック
母集団分布が既知である確率分布(例えば、二項分布や正規分布など)に従うことが明らかであるとき、母集団分布を母数の推定を行うことで解釈できる。このような分布を**パラメトリック**という。  
一方で、上記に当てはまらない分布を**ノンパラメトリック**という。この場合は分布を仮定しなくても算術可能な記述統計量で母集団分布を解釈する。

# 母数・統計量

## 母数
パラメトリックな分布において、母集団分布は確率密度関数が定義できるような確率分布であることを述べた。この確率密度関数は$X=x$における確率値を表すほか、分布の性質を表す関数としても表すことができる。例えば、正規分布の$\mu, \sigma^{2}$はその平均値および分散を表している([参考](%E7%A2%BA%E7%8E%87%E5%88%86%E5%B8%83.qmd#正規分布))。このように、確率分布の特性を表す変数を**母数(パラメータ)**と呼ぶ。多くの場合、母数は未知であるため、統計的推測はこの母数を標本からどのようにして明らかにするかというところをフォーカス @fig-estimate する。  
※他の確率分布の母数については、[こちら](%E7%A2%BA%E7%8E%87%E5%88%86%E5%B8%83.qmd#分布の平均値・分散)にまとめている。

## 統計量
**統計量**とは標本を要約したものである。ここでは未知のパラメータは含まずに、標本からのみ得られる数値のことを指す。統計量として考えられるものとして、平均・分散・標準偏差・メディアン・モード・最大値・最小値・四分位点・相関係数など様々なものがある。  
これらは総じて標本$x_{1}, x_{2}, \cdots, x_{n}$を統計量に変換する写像$g(x_{1}, x_{2}, \cdots, x_{n})$と考えることができる。何パターンかの標本から算出される統計量$g(x_{1}, x_{2}, \cdots, x_{n})$を集めて生成される確率分布を**標本分布**という。

## 標本平均・標本分散
標本$x_{1}, x_{2}, \cdots, x_{n}$から算出する平均を**標本平均**と呼び、 @eq-mean で定義する。また、同様に標本から算出する分散を**標本分散(不偏分散)**と呼び、 @eq-variance で定義する。  
※不偏分散の$n - 1$を未知変数の数を意味する**自由度**と呼ぶ。

$$
\bar{x} = \frac{1}{n} \sum^{n}_{i = 1} x_{i}
$${#eq-mean}

$$
s^{2} = \frac{1}{n - 1} \sum^{n}_{i = 1} (x_{i} - \bar{x})
$${#eq-variance}

::: {.callout-note}
## 標本平均・標本分散の標本分布

### 標本平均
標本平均の平均値について、$E(\bar{x}) = \mu$が成立する。これは、$\bar{x}$が母集団分布の平均$\mu$を正しく推定することを表している。  
また、標本平均の分散について、$V(\bar{x}) = \frac{\sigma^{2}}{n}$が成立する。これは、$\bar{x}$が母集団分布の分散$\sigma^{2}$をサンプルサイズ$n$の分だけ過小評価することを表している。  
これらを踏まえると、$n \rightarrow \infty \Rightarrow E(\bar{x}) \rightarrow \mu, V(\bar{x}) \rightarrow 0$が成立する。これは、サンプルサイズが増えるほど標本平均の標本分布は母集団分布の平均値$\mu$に集中して局在するような傾向があるということである([大数の法則](%E4%B8%AD%E5%BF%83%E6%A5%B5%E9%99%90%E5%AE%9A%E7%90%86.qmd#大数の(弱)法則))。

### 標本分散
標本分散の平均値について、$E(s^{2}) = \sigma^{2}$が成立する。これは、$s^{2}$が母集団分布の分散$\sigma^{2}$を正しく推定することを表している。これにより、 @eq-variance は**不偏分散(不偏推定量)** と呼ぶ。  
一方で、 @eq-variance2 のような標本分散も定義できる。この場合は$E(S^{2}) = \frac{n - 1}{n} \sigma^{2}$となり、母集団分布の分散より過小評価される。

$$
S^{2} = \frac{1}{n} \sum^{n}_{i = 1} (x_{i} - \bar{x})
$${#eq-variance2}

:::

# 推定
未知である母数を推定するために標本から算出された統計量を**推定量**$\hat{\theta}$と呼ぶ。推定量は大まかに分けるとピンポイントに母数を推定する**点推定**と、真の母数が得られる確率を保証する区間を求める**区間推定**の二種類ある。

## 点推定
$E(\bar{x}) = \mu, E(s^{2}) = \sigma^{2}$が成り立つことは既に述べた。これにより、標本平均および不偏分散はそれぞれ母集団分布の平均および分散の推定量である。これは、実際の観測から得られたデータで算出することができる。このようにして得られる値を**推定値**と呼ぶ。  
次に、平均・分散以外のあらゆる母数について、推定値から真の母数に近い値を推定するために次の**最尤法**を導入する。

母集団分布の確率密度関数$f(x; \theta)$に対して、実際に得られた標本$x_{1}, x_{2}, \cdots, x_{n}$を用いて$n$個の確率関数$f(x_{i}; \theta) \ (i = 1, 2, \cdots, n)$を生成する。このとき、$x_{i}$は定数なので確率関数を母数$\theta$は関数であることに注意する。また、母数がとりうる値の範囲$\Theta$を**母数空間**と呼ぶ。  
次に、確率関数の積 @eq-likehood を導入する。この$L(\theta)$を**尤度**という。最尤法は母数空間の範囲でこの尤度関数を最大化する**最尤推定量**$\tilde{\theta}$を求めることを目的とする。

$$
L(\theta) = \prod^{n}_{i = 1} f(x_{i}; \theta)
$${#eq-likehood}

実際に最尤推定量を求める際には尤度関数の対数をとった**対数尤度**$\log{L(\theta)}$を使用する。この対数尤度(尤度も)は上に凸なので、**尤度方程式** @eq-max-likehood を解くことによって最尤推定量を算出することができる。

$$
\frac{\partial}{\partial \theta} \log{L(\theta)} = 0
$${#eq-max-likehood}

::: {.callout-note}
## 最尤原理

これら最尤法には「現実の標本は確率最大のものが実現した」という**最尤原理**の仮定が用いられている。これは、標本から得られる推定量は真の母数の近い位置に局在するというものである。
:::

## 区間推定
区間推定は真の母数$\theta$が、$1 - \alpha$の確率で含まれるある区間$(l, u)$を推定すること @eq-confidence である。ここでの$\alpha$は母数が区間に含まれない確率である。また、確率変数$l$を**下側信頼限界**、確率変数$u$を**上側信頼限界**、$1 - \alpha$を**信頼係数**、区間$[l, u]$を$100 * (1 - \alpha)$%**信頼区間**と呼ぶ。

$$
P(l \leqq \theta \leqq u) \geqq 1 - \alpha
$${#eq-confidence}

::: {.callout-note}
## 信頼区間

信頼区間は標本によって変化するので、「母数$\theta$が、$1 - \alpha$の確率で含まれる区間」が常に得られるわけではない。信頼区間の正しい解釈は「多くの標本に対して算出された信頼区間が$\theta$を包含する確率が$1 - \alpha$になる」というものである。これは、標本を得れば得るほど信頼区間の信頼性が増し、母数の推定において強力なエピデンスになるということである。  
また、信頼区間の幅はサンプルサイズ$n$に対して、多くの場合オーダー$\frac{1}{\sqrt{n}}$で$0$に近づく(オーダーがかわっても幅は$0$に漸近する)。即ち、サンプルサイズが大きいほど母数$\theta$を正確に推定できる。
:::